name: CI Pipeline

on:
   push:
jobs:
   run-ci-job:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Display CI message
          run: echo "CI Pipeline Executed Successfully"
