name: CI Pipeline

on:
   push:
jobs:
   run-ci-job:
      runs-on: ubuntu-latest

      steps:
        -name: checkout Repository
         uses: actions/checkout@v3

        -name: Display CI message
         uses: echo "CI Pipeline Executed Successfully"
